#ifndef _MEMORY_CONFIG_H_
#define _MEMORY_CONFIG_H_

#define PHYSICAL_ADDRESS_BASE ((u_longlong)0x80000000)
#define PHYSICAL_MEMORY_SIZE ((u_longlong)0x08000000)
#define PHYSICAL_MEMORY_TOP (PHYSICAL_ADDRESS_BASE + PHYSICAL_MEMORY_SIZE)
#define KERNEL_STACK_SIZE 0x80000

#define PAGE_SHIFT 12
#define PAGE_SIZE (1 << PAGE_SHIFT)
#define PHYSICAL_PAGE_NUM (PHYSICAL_MEMORY_SIZE >> PAGE_SHIFT)


#define KERNEL_ADDRESS_TOP (1L << 38)
#define TRAMPOLINE_BASE (KERNEL_ADDRESS_TOP - (PAGE_SIZE << 1))

#define KERNEL_STACK_TOP (PHYSICAL_MEMORY_TOP + KERNEL_STACK_SIZE)
#define USER_STACK_TOP TRAMPOLINE_BASE
#endif